import type { SectionContentMap, SectionType } from "./config";

// Friendly labels + starter content for each section type (used when a client
// adds a new section from the page editor).
export const SECTION_META: { type: SectionType; label: string; description: string }[] = [
  { type: "banner", label: "Page banner", description: "Page title header with optional background image, colour & opacity." },
  { type: "hero", label: "Hero banner", description: "Big headline, image and call-to-action buttons." },
  { type: "about", label: "About / text + image", description: "Two-column text with bullet points and an image." },
  { type: "serviceCategories", label: "Services grid", description: "Your services grouped by category." },
  { type: "stats", label: "Stats counters", description: "Numbers like projects done, happy customers." },
  { type: "gallery", label: "Gallery", description: "Photos grouped by category." },
  { type: "steps", label: "How it works", description: "Numbered step-by-step process." },
  { type: "cta", label: "Call-to-action band", description: "Phone numbers + a button strip." },
  { type: "team", label: "Team / people", description: "Doctors, trainers, faculty or consultants." },
  { type: "priceList", label: "Price list / menu", description: "Menu, course fees or packages with prices." },
  { type: "features", label: "Why choose us", description: "Icon feature cards (quality, on-time, etc.)." },
  { type: "testimonials", label: "Testimonials", description: "Customer reviews with ratings." },
  { type: "faq", label: "FAQ", description: "Frequently asked questions accordion." },
  { type: "logos", label: "Partner logos", description: "Row of partner/brand names." },
  { type: "video", label: "Video", description: "Embed a YouTube or video URL." },
  { type: "imageBanner", label: "Image banner + CTA", description: "Full-width image with heading and button." },
  { type: "contactInfo", label: "Contact info + map", description: "Address, phone, email, hours and a map." },
  { type: "quoteForm", label: "Quote form", description: "Lead capture form with a sidebar." },
  { type: "contactForm", label: "Contact form", description: "Contact details + a message form." },
  { type: "appointmentForm", label: "Appointment form", description: "Booking form with date & time." },
  { type: "noticeBoard", label: "Notice board", description: "Live notices — results, admissions, events & holidays with date & tags." },
  { type: "toppers", label: "Toppers / results", description: "Showcase top students with photo, rank and score (medals)." },
  { type: "downloads", label: "Downloads / prospectus", description: "Downloadable files — prospectus, syllabus, fee structure, forms." },
  { type: "pricingPlans", label: "Pricing plans", description: "Subscription-style pricing cards with feature lists." },
  { type: "openingHours", label: "Opening hours", description: "Weekly business hours table." },
  { type: "countdown", label: "Countdown timer", description: "Live countdown to an event / offer deadline." },
  { type: "map", label: "Map", description: "Full-width Google Map embed with address." },
  { type: "richText", label: "Rich text / HTML", description: "Free-form HTML content block." },
];

export const SECTION_DEFAULTS: { [K in SectionType]: SectionContentMap[K] } = {
  banner: {
    title: "Page",
    titleHighlight: "Title",
    subtitle: "",
    image: "",
    bgColor: "",
    imageOpacity: 35,
    overlayOpacity: 75,
  },
  hero: {
    variant: "classic",
    customHtml: "",
    badge: "PROFESSIONAL · RELIABLE · AFFORDABLE",
    titleTop: "Your Headline Here",
    titleHighlight: "Highlighted Part",
    subtitle: "",
    description: "A short supporting line about your services.",
    image: "",
    primaryBtn: { label: "Call Now", href: "tel:0000000000" },
    secondaryBtn: { label: "Our Services", href: "/services" },
    features: [
      { icon: "badge-check", title: "Quality Work", text: "" },
      { icon: "clock", title: "On-Time", text: "" },
    ],
    slides: [
      { titleTop: "Welcome to", titleHighlight: "Our Business", description: "A short line about what makes you the best choice.", image: "", primaryBtn: { label: "Get Started", href: "/contact" }, secondaryBtn: { label: "Learn More", href: "/about" } },
      { titleTop: "Quality You", titleHighlight: "Can Trust", description: "Highlight a second offer, service or promotion here.", image: "", primaryBtn: { label: "Call Now", href: "tel:0000000000" }, secondaryBtn: { label: "Our Services", href: "/services" } },
    ],
  },
  about: {
    eyebrow: "ABOUT US",
    title: "About",
    titleHighlight: "Us",
    body: ["Write about your business here."],
    image: "",
    points: ["Point one", "Point two"],
    buttonLabel: "Learn more",
    buttonHref: "/about",
  },
  serviceCategories: { eyebrow: "OUR SERVICES", title: "Our", titleHighlight: "Services", categories: [] },
  stats: {
    items: [
      { value: "100+", label: "Projects", icon: "home" },
      { value: "100%", label: "Happy Customers", icon: "users" },
    ],
  },
  gallery: { eyebrow: "", title: "Our", titleHighlight: "Gallery" },
  steps: {
    eyebrow: "",
    title: "How It",
    titleHighlight: "Works",
    items: [
      { title: "Step 1", text: "Describe step 1", icon: "edit" },
      { title: "Step 2", text: "Describe step 2", icon: "check" },
    ],
  },
  cta: { title: "Need Any Help?", highlight: "We're Just a Call Away", phones: ["0000000000"], buttonLabel: "Get Free Quote", buttonHref: "/quote" },
  team: {
    eyebrow: "OUR TEAM",
    title: "Meet Our",
    titleHighlight: "Team",
    members: [
      { name: "Full Name", role: "Role / Designation", image: "", note: "" },
      { name: "Full Name", role: "Role / Designation", image: "", note: "" },
    ],
  },
  priceList: {
    eyebrow: "",
    title: "Our",
    titleHighlight: "Pricing",
    note: "",
    groups: [
      { category: "Category", items: [{ name: "Item", price: "₹0", note: "" }] },
    ],
  },
  quoteForm: { title: "Request Your Free Quote", subtitle: "Tell us about your requirement.", showSidebar: true },
  contactForm: { title: "Contact Us", subtitle: "We'd love to hear from you." },
  appointmentForm: { title: "Book an Appointment", subtitle: "Pick a date and time that suits you." },
  faq: { eyebrow: "FAQ", title: "Frequently Asked", titleHighlight: "Questions", items: [{ q: "Question?", a: "Answer." }] },
  testimonials: { eyebrow: "TESTIMONIALS", title: "What Our Customers", titleHighlight: "Say", items: [
    { name: "Customer Name", role: "Happy Customer", text: "Excellent service — highly recommended!", rating: 5 },
  ] },
  logos: { title: "Trusted by leading partners", items: ["Partner 1", "Partner 2", "Partner 3", "Partner 4"] },
  features: { items: [
    { icon: "badge-check", title: "Quality Work", text: "We never compromise on quality." },
    { icon: "clock", title: "On-Time Service", text: "We respect your time." },
    { icon: "shield", title: "Trusted Team", text: "Experienced & verified professionals." },
    { icon: "tag", title: "Affordable", text: "Best price guarantee." },
  ] },
  video: { eyebrow: "WATCH", title: "See Us", titleHighlight: "In Action", url: "", caption: "" },
  imageBanner: { title: "Ready to get started?", subtitle: "Contact us today for a free consultation.", buttonLabel: "Get Free Quote", buttonHref: "/quote", image: "" },
  contactInfo: { eyebrow: "REACH US", title: "Get In", titleHighlight: "Touch", address: "Your address here", phone: "0000000000", email: "hello@example.com", hours: "Mon–Sat: 9am – 7pm", mapEmbed: "" },
  richText: { html: "<p>Write your content here.</p>" },
  html: { code: "<div>Custom HTML</div>" },
  pricingPlans: {
    eyebrow: "PRICING",
    title: "Our",
    titleHighlight: "Plans",
    plans: [
      { name: "Basic", price: "₹999", period: "/month", features: ["Feature one", "Feature two"], featured: false, buttonLabel: "Choose", buttonHref: "/quote" },
      { name: "Standard", price: "₹1,999", period: "/month", features: ["Everything in Basic", "Feature three", "Feature four"], featured: true, buttonLabel: "Choose", buttonHref: "/quote" },
      { name: "Premium", price: "₹3,499", period: "/month", features: ["Everything in Standard", "Priority support"], featured: false, buttonLabel: "Choose", buttonHref: "/quote" },
    ],
  },
  openingHours: {
    eyebrow: "TIMINGS",
    title: "Opening",
    titleHighlight: "Hours",
    note: "",
    days: [
      { day: "Monday – Friday", hours: "9:00 AM – 7:00 PM" },
      { day: "Saturday", hours: "10:00 AM – 5:00 PM" },
      { day: "Sunday", hours: "Closed" },
    ],
  },
  countdown: {
    eyebrow: "",
    title: "Limited Time",
    titleHighlight: "Offer",
    subtitle: "Hurry — offer ends soon!",
    targetDate: "",
    buttonLabel: "Grab the offer",
    buttonHref: "/quote",
  },
  map: { eyebrow: "", title: "Find", titleHighlight: "Us", address: "Your address here", mapEmbed: "" },
  noticeBoard: {
    eyebrow: "STAY UPDATED", title: "Notice", titleHighlight: "Board",
    notices: [
      { date: "10 Jul 2026", title: "Class 10 & 12 Board Results declared — congratulations!", category: "Result", link: "/results", isNew: true },
      { date: "05 Jul 2026", title: "Admissions open for the new session — apply online", category: "Admission", link: "/admission", isNew: true },
      { date: "28 Jun 2026", title: "Annual Day celebration on 20th July", category: "Event", link: "", isNew: false },
      { date: "20 Jun 2026", title: "Summer break — school reopens on 1st July", category: "Holiday", link: "", isNew: false },
    ],
  },
  toppers: {
    eyebrow: "OUR PRIDE", title: "Our", titleHighlight: "Toppers",
    items: [
      { name: "Student Name", exam: "Class 12 · Science", score: "98.6%", rank: "1", image: "" },
      { name: "Student Name", exam: "Class 12 · Commerce", score: "97.8%", rank: "2", image: "" },
      { name: "Student Name", exam: "Class 10 · CBSE", score: "98.2%", rank: "1", image: "" },
      { name: "Student Name", exam: "Class 10 · CBSE", score: "97.4%", rank: "2", image: "" },
    ],
  },
  downloads: {
    eyebrow: "DOWNLOADS", title: "Downloads &", titleHighlight: "Prospectus",
    items: [
      { title: "Prospectus 2026–27", description: "Everything about our programs, facilities & admissions.", link: "", icon: "book" },
      { title: "Admission Form", description: "Fill and submit the offline admission form.", link: "", icon: "clipboard" },
      { title: "Fee Structure", description: "Class-wise fee details and payment options.", link: "", icon: "tag" },
      { title: "Academic Calendar", description: "Holidays, exams and events for the year.", link: "", icon: "calendar" },
    ],
  },
};
